### ISSUE TITLE
Can't generate graph image with docker image. 

### ISSUE THREAD

**Issue by rwblair** [poldracklab/preprocessing-workflow#82]
Graphviz may not be installed:

Traceback (most recent call last):
  File "/usr/local/miniconda2/envs/crnenv/bin/fmriprep", line 9, in <module>
    load_entry_point('fmriprep', 'console_scripts', 'fmriprep')()
  File "/root/src/preprocessing-workflow/fmriprep/run_workflow.py", line 162, in main
    workflow.write_graph()
  File "/usr/local/miniconda2/envs/crnenv/lib/python2.7/site-packages/nipype/pipeline/engine/workflows.py", line 444, in write_graph
    format_dot(dotfilename, format=format)
  File "/usr/local/miniconda2/envs/crnenv/lib/python2.7/site-packages/nipype/pipeline/engine/utils.py", line 1044, in format_dot
    raise IOError("Cannot draw directed graph; executable 'dot' is unavailable")
IOError: Cannot draw directed graph; executable 'dot' is unavailable

**Comment by oesteban** [comment]
Latest image of ```oesteban/crn_nipype``` has graphviz. Should work if you re-build your docker image.
